//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalInformation
    {
        public int AddRecordingId { get; set; }
        public int PetId { get; set; }
        public int InformationTypeId { get; set; }
        public int RecordingId { get; set; }
    
        public virtual InformationBirds InformationBirds { get; set; }
        public virtual InformationReptiles InformationReptiles { get; set; }
        public virtual InformationTypes InformationTypes { get; set; }
        public virtual Pets Pets { get; set; }
    }
}
