//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zoo_PracticeEntities : DbContext
    {
        public Zoo_PracticeEntities()
            : base("name=Zoo_PracticeEntities")
        {
        }
        private static Zoo_PracticeEntities _context;
        public static Zoo_PracticeEntities GetContext()
        {
            if (_context == null)
                _context = new Zoo_PracticeEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalInformation> AdditionalInformation { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Diets> Diets { get; set; }
        public virtual DbSet<DietTypes> DietTypes { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Habitats> Habitats { get; set; }
        public virtual DbSet<InformationBirds> InformationBirds { get; set; }
        public virtual DbSet<InformationReptiles> InformationReptiles { get; set; }
        public virtual DbSet<InformationTypes> InformationTypes { get; set; }
        public virtual DbSet<Pets> Pets { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
